In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]

In [ ]:
a*a

array([1, 4, 9])

In [ ]:
np.dot(a,a) #vector multiplication; vectorized = bc

14

In [ ]:
dataset = pd.read_csv('movies.csv', encoding='utf-8')

In [ ]:
dataset.drop(['color'], axis=1, inplace=True)

In [ ]:
for i in dataset['director_name']: #not vectorized fns = can't do computation in parallel. doesn't use matrix operations.
    #so avoid using often
    print(i)

Martin Scorsese
Shane Black
Quentin Tarantino
Kenneth Lonergan
Peter Jackson
nan
Peter Jackson
Edward Hall
Joss Whedon
Joss Whedon
Tom Tykwer
Null
Christopher Spencer
Christopher Nolan
F. Gary Gray
Richard Linklater
Quentin Tarantino
Michael Bay
Christopher Nolan
Peter Jackson
Tom Hooper
Tom Hooper
Kathryn Bigelow
Ridley Scott
nan
Michael Bay
Denis Villeneuve
Gnana Rajasekaran
Marc Webb
Nan
Ridley Scott
Ridley Scott
nan
Mike Leigh
Gore Verbinski
David Fincher
Bryan Singer
Jay Oliva
Christopher Nolan
Paul Thomas Anderson
Sam Mendes
nan
Michael Patrick King
Tate Taylor
Francis Lawrence
Steven Spielberg
Michael Bay
Guillaume Canet
Paul Thomas Anderson
Bryan Singer
Adam McKay
Zack Snyder
Sam Mendes
Sam Mendes
Baz Luhrmann
Baz Luhrmann
nan
Steven Spielberg
Marc Webb
nan
Joss Whedon
Timur Bekmambetov
Timur Bekmambetov
Timur Bekmambetov
Justin Chadwick
Oliver Stone
David Dobkin
Ryan Murphy
James Wan
Derek Cianfrance
Gavin O'Connor
nan
Gary Ross
Tate Taylor
Terrence Malick
nan
Robert Zemeckis
Darren Aronofsky
Martin Scorsese
Ridley Scott
James Mangold
Daniel Espinosa
nan
Walter Salles
nan
Angelina Jolie Pitt
Angelina Jolie Pitt
Seth MacFarlane
Anthony Russo
Rob Marshall
Adam Shankman
nan
Sadyk Sher-Niyaz
Tony Gilroy
Steve McQueen
Richard J. Lewis
Paul Greengrass
David Ayer
Clint Eastwood

In [ ]:
dataset['director_name'].fillna('', inplace=True)

In [ ]:
dataset

,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
1,Shane Black,195,408992272.0,Action|Adventure|Sci-Fi,Iron Man 3,2013,English,USA,200000000.0,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000
2,Quentin Tarantino,187,54116191.0,Crime|Drama|Mystery|Thriller|Western,The Hateful Eight,2015,English,USA,44000000.0,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000
3,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,usa,14000000.0,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0
4,Peter Jackson,186,258355354.0,Adventure|Fantasy,The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000
...,...,...,...,...,...,...,...,...,...,...,...,...
94,Steve McQueen,134,56667870.0,Biography|Drama|History,12 Years a Slave,2013,English,USA,20000000.0,8.1,"Quvenzhané Wallis,Scoot McNairy,Taran Killam",83000
95,Richard J. Lewis,134,7501404.0,Comedy|Drama,Barney's Version,2010,English,Canada,NaN,7.3,"Mark Addy,Atom Egoyan,Paul Gross",0
96,Paul Greengrass,134,107100855.0,Biography|Drama|Thriller,Captain Phillips,2013,English,USA,55000000.0,7.9,"Tom Hanks,Chris Mulkey,Michael Chernus",65000
97,David Ayer,134,85707116.0,Action|Drama|War,Fury,2014,English,USA,68000000.0,7.6,"Brad Pitt,Logan Lerman,Jim Parrack",82000
98,Clint Eastwood,5,47034272.0,Biography|Drama|Music|Musical,Jersey Boys,2014,English,USA,40000000.0,6.9,"Johnny Cannizzaro,Steve Schirripa,Scott Vance",16000